### ISSUE TITLE
Form state ramain invalid

### ISSUE THREAD

**Issue by pramodEE** [SKaDiZZ/ngx-iban-validator#5]
The validator works as per expected but if the input is valid still gets an error object which causes breaks other checks. like, disable button.

![image](https://github.com/SKaDiZZ/ngx-iban-validator/assets/77338781/c88634f3-56fa-47ac-acbe-996b6ca496d0)

**Comment by pramodEE** [comment]
> The validator works as per expected but if the input is valid still gets an error object which causes breaks other checks. like, disable button.
> 
> ![image](https://user-images.githubusercontent.com/77338781/249694062-c88634f3-56fa-47ac-acbe-996b6ca496d0.png)

If I update lines as follows it working fine but then test need to be write again.

![image](https://github.com/SKaDiZZ/ngx-iban-validator/assets/77338781/949f0355-0e40-4621-be9e-6dac266c87ba)

**Comment by SKaDiZZ** [comment]
Thank you for reporting this issue, I have just released update to fix it. So just try installing version 1.1.16 it should fix your issue.
